
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/lib/jvm/java-21-openjdk/bin/"
      - "/home/enam/.local/bin/"
      - "/home/enam/.atuin/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/home/enam/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/bin/"
    searched_directories:
      - "/usr/lib/jvm/java-21-openjdk/bin/uname"
      - "/home/enam/.local/bin/uname"
      - "/home/enam/.atuin/bin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/lib/jvm/java-21-openjdk/bin"
        - "/home/enam/.local/bin"
        - "/usr/lib/jvm/java-21-openjdk/bin"
        - "/home/enam/.atuin/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/home/enam/.config/Code/User/globalStorage/github.copilot-chat/debugCommand"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.16.4-zen1-1-zen - x86_64
...
